#!/usr/bin/env python

import matplotlib.mlab as ml
import numpy as np
import sys

def get_sightings(filename, focusbiosig):

    # # Load table
    # tab = ml.csv2rec(filename)

    # focusbiosig = focusbiosig.capitalize()

    # # Find number of records and total count of BioSignatures seen
    # isfocus = (tab['BioSignature'] == focusbiosig)
    # totalrecs = np.sum(isfocus)
    # if totalrecs == 0:
    #     meancount = 0
    # else:
    #     meancount = np.mean(tab['count'][isfocus])

    # # Return num of records and biosignatures seen
    # return totalrecs, meancount


    # Load table
    tab = ml.csv2rec(filename)


    # Loop through all records, countings recs and biosignatures
    totalrecs = 0.
    totalcount = 0.
    focusbiosig = focusbiosig.capitalize()

    for rec in tab:
        if rec['BioSignature'] == focusbiosig:
            totalrecs += 1
            totalcount += rec['count']

    if totalrecs == 0:
        meancount = 0
    else:
        meancount = totalcount/totalrecs
    # Return num of records and biosignatures seen
    return totalrecs, meancount


filename = sys.argv[1]
biosig = sys.argv[2]

print get_sightings(filename, biosig)
